//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dietaverse.View
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_summary
    {
        public int Id { get; set; }
        public Nullable<int> kcal_amount { get; set; }
        public Nullable<double> weight { get; set; }
        public string notes { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual users users { get; set; }
        public virtual months months { get; set; }
    }
}
