//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dietaverse.View
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipes_ingredient
    {
        public int Id { get; set; }
    
        public virtual smoothies_recipes smoothies_recipes { get; set; }
        public virtual smoothies_ingr smoothies_ingr { get; set; }
    }
}
