//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dietaverse.View
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_dishes_gallery
    {
        public int Id { get; set; }
    
        public virtual users users { get; set; }
        public virtual dishes_gallery dishes_gallery { get; set; }
    }
}
